### ISSUE TITLE
index.js is treated as an ES module file as it is a .js file

### ISSUE THREAD

**Issue by Dev-Akash** [ayda-tech/react-share-kit#16]
> index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
> Instead either rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs"

So this is the error coming while implementing in next js application.
On my local have removed the "type": "module " line from package.json 

Please let me know if this can be resolved as on deploying it is giving issue.

Thank you!

**Comment by ybhrdwj** [comment]
Did you find any solution to this? I'm getting the same error

**Comment by ybhrdwj** [comment]
I was facing same issue, resolved by the following way:
added `/dist/index.js` in the import statement `'react-share-kit/dist/index.es'`

**Comment by kaybrian** [comment]
- actually, this is a life saver for this package, i am not sure why the error is there.

**Comment by khayargoli** [comment]
I still have this issue in my next.js 14 application, any solution?
